Registration_TEL_DTAC.pdf: genpdf_registration_postpaid.ini
Registration_TEL_DTN.pdf: genpdf_registration_postpaid.ini
Registration_PRE_DTAC.pdf: genpdf_registration_prepaid.ini
Registration_PRE_DTN.pdf: genpdf_registration_prepaid.ini
Registration_PRE_Template.pdf: genpdf_registration_pre_template.ini
Consent_ANY_DTN.pdf: genpdf_consent.ini
Device_Sales_DTAC.pdf: genpdf_device_sales.ini
Device_Sales_DTN.pdf: genpdf_device_sales.ini
Device_Sales_DTAC_2018.pdf: genpdf_device_sales_2018.ini
Device_Sales_DTN_2018.pdf: genpdf_device_sales_2018.ini
Device_Sales_DTN_2019.pdf: genpdf_device_sales_2019.ini
Device_Sales_DTN_2021.pdf: genpdf_device_sales_2021.ini
Nice_Number_DTAC.pdf: genpdf_nice_number.ini
Nice_Number_DTN.pdf: genpdf_nice_number.ini
Nice_Number_DTAC_2018.pdf: genpdf_nice_number_2018.ini
Nice_Number_DTN_2018.pdf: genpdf_nice_number_2018.ini
Nice_Number_DTN_202209.pdf: genpdf_nice_number_202209.ini
Change_Sim_DTAC_2018.pdf: genpdf_change_sim_dtac.ini
Port2Trinet_DTN.pdf: genpdf_port_to_trinet_dtn.ini
Change_Sim_062018.pdf: genpdf_change_sim_062018.ini
MNP_DTN.pdf: genpdf_mnp.ini
Change_Owner_PRE.pdf: genpdf_change_owner_prepaid.ini
WithholdingTax_Subscription.pdf: genpdf_wiitholding_tax_subscription.ini
WithholdingTax_Unsubscription.pdf: genpdf_wiitholding_tax_unsubscription.ini
Consent_Check_Blacklist.pdf: genpdf_consent_check_blacklist.ini
Request_Adjust_Service_Changing.pdf: genpdf_request_adjust_service_changing.ini
Request_Adjust_Service_Changing_Copporate.pdf: genpdf_request_adjust_service_changing_copporate.ini
Consent_MDID.pdf: genpdf_consent_mdid.ini
UnConsent_MDID.pdf: genpdf_unconsent_mdid.ini
Dtac_Broadband_Register.pdf: genpdf_dtac_broadband_register.ini
Device_Sales_With_Device_Financing.pdf: genpdf_device_sales_with_device_financing.ini
Device_Sales_042022.pdf: genpdf_device_sales_042022.ini
Consent_MDID_042022.pdf: genpdf_consent_mdid_042022.ini
UnConsent_MDID_042022.pdf: genpdf_unconsent_mdid_042022.ini
Device_contract_052022.pdf: genpdf_device_contract_052022.ini
Device_contract_122022.pdf: genpdf_device_contract_122022.ini
Switch_Off_Template.pdf: genpdf_switch_off_template.ini
xsimRegister_Consent_EN.pdf: genpdf_xsimRegister_Consent_EN.ini
xsimRegister_Consent_TH.pdf: genpdf_xsimRegister_Consent_TH.ini
xSimConsent_202306_EN.pdf: genpdf_xSimConsent_202306_EN.ini
xSimConsent_202306_TH.pdf: genpdf_xSimConsent_202306_TH.ini
default: genpdf.ini
